### ISSUE TITLE
2013 Dataset redirects to login page

### ISSUE THREAD

**Issue by seekayel** [CityOfPhiladelphia/campaign-finance-data-cleanup#1]
When you click on the 2013 dataset in the README.MD:

https://data.phila.gov/Government/2013ytd/9pan-2k8k

You get redirected to the Socrata Datalens login page (https://data.phila.gov/login)

I'm guessing that the permissions aren't set correctly on that page.

**Comment by nwebz** [comment]
@seekayel: You are right, I have adjusted the permissions, sorry for the inconvenience.

**Comment by seekayel** [comment]
Woot 👍🏻
